version: '3.4'

services:
  sortasc.worker.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - KafkaJobsQueueOptions__BootstrapServers=kafka:9095
      - Redis__ConnectionString=redis:6379
    depends_on:
      - "kafka"
      - "redis"
    ports:
      - "6030:80"
      - "6031:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  sortasc.worker.service.replica:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - KafkaJobsQueueOptions__BootstrapServers=kafka:9095
      - Redis__ConnectionString=redis:6379
    depends_on:
      - "kafka"
      - "redis"
    ports:
      - "6020:80"
      - "6021:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sortingwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KafkaJobsQueueOptions__BootstrapServers=kafka:9095
      - Redis__ConnectionString=redis:6379
    depends_on:
      - "kafka"
      - "redis"
    ports:
      - "6010:80"
      - "6011:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9095'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9095
      - KAFKA_CFG_NUM_PARTITIONS=20
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - "zookeeper"
 
  redis:
        image: redis:latest
        ports:
            - "6379"
        volumes:
            - ./Redis/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]